version: '3.8'

services:
  komoot:
    container_name: komoot-app
    restart: always
    stdin_open: true
    build:
      context: ../
      dockerfile: ./.docker/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - komoot:/app

volumes:
  komoot: